name: Sync and Keep Alive

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4 to fix the Node.js warning
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub and Wake Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Use the token to push to the Space
          git push --force https://Vijayshete04:$HF_TOKEN@huggingface.co/spaces/Vijayshete04/Multimodal-AI-Medical-Assistant main
          
          # Wake up the space
          curl -I -L https://huggingface.co/spaces/Vijayshete04/Multimodal-AI-Medical-Assistant